### ISSUE TITLE
[Errno 2] No such file or directory: 'ldm_vae/models/first_stage_models/vq-f4/model.ckpt'

### ISSUE THREAD

**Issue by ahmad786writes** [puckikk1202/difffacesketch2023#16]
Traceback (most recent call last):
  File "D:\Umer\updated_code\Crimsniffer\difffacesketch2023-master\test_sketchdiff_ddim.py", line 159, in <module>
    main()
  File "D:\Umer\updated_code\Crimsniffer\difffacesketch2023-master\test_sketchdiff_ddim.py", line 47, in main
    ae = get_model()
  File "D:\Umer\updated_code\Crimsniffer\difffacesketch2023-master\test_sketchdiff_ddim.py", line 38, in get_model
    model = load_model_from_config(config, "ldm_vae/models/first_stage_models/vq-f4/model.ckpt")
  File "D:\Umer\updated_code\Crimsniffer\difffacesketch2023-master\test_sketchdiff_ddim.py", line 27, in load_model_from_config
    pl_sd = torch.load(ckpt)#, map_location="cpu")
  File "C:\Users\GIFT\anaconda3\envs\SGLDM\lib\site-packages\torch\serialization.py", line 1065, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\GIFT\anaconda3\envs\SGLDM\lib\site-packages\torch\serialization.py", line 468, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\GIFT\anaconda3\envs\SGLDM\lib\site-packages\torch\serialization.py", line 449, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'ldm_vae/models/first_stage_models/vq-f4/model.ckpt'

**Comment by puckikk1202** [comment]
you can download the ckpt in this repo [LDM](https://github.com/CompVis/latent-diffusion?tab=readme-ov-file)
